import jsPDF from "jspdf";

export const ROBOTO_REGULAR_B64 = 
    "AAEAAAASAQAABAAwR0RFRgBAACoAAAHIAAAAKEdQT1OFrIdpAAAH8AAAALZHU1VClE6S" +
    "bQAADQgAAAD0T1MvMoideAgAAAGsAAAAYGNtYXBoBsIqAAADPAAAAGxjY2FwAAAAAABA" +
    "AAAAAXN0bXQAAGYwAAADmAAAACZjbWFwBwYFBAAAA9wAAAGwZ2FzcAAAABAAAAHAAAAA" +
    "CGdseWb7lFisAAAIgAAAFjRoZWFk/4uChwAAARwAAAA2aGhlYQceA90AAAEsAAAAJGht" +
    "dHi0SgL4AAAB3AAAAGRsb2NhAKwB6AAAAagAAABkbWF4cAFXAM4AAAFYAAAAIG5hbWUY" +
    "i0GIAAAL6AAAAkZwb3N0/+wAZQAAAdwAAAAgcGVuZAEBAQEA//8AAP//AAAAAQAAAAgA" +
    "AwAGAAAAAAACAAAAAwAFAAEAAQAAAAAAAAAOAAAAAQAAAAAAAwAEAAsAAQABAAAAAAAE" +
    "AAQAEQABAAEAAAAAAAUABAAZAAEAAQAAAAAABgAEAAsAAQABAAAAAAAKAAwAIQABAAAA" +
    "AAALAAwALQABAAAAAAAMAAwAOQABAAAAAAANAAwARQABAAEAAAAAAA4ABAALAAEAAQAA" +
    "AAAADwAEABUAAQABAAAAAAAQAAwAGQABAAEAAAAAABEABAAlaXNvbgEAAQAFAAYABwAI" +
    "AAkACgALAAwADQAOAA8AEAARAAgACwACAAUAAwAEAAoACQAHAAYACwAMAA0ADgAPABA=";

export function addingFontToDoc(doc : jsPDF) {
    doc.addFileToVFS('Roboto-Regular.ttf', ROBOTO_REGULAR_B64);
    doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal');
    doc.setFont('Roboto');
}