import { Promotion } from '../promotion/PromotionsPage';
export const mockPromotions: Promotion[] = [
    {
        id: 1,
        code: 'BOOK2026',
        name: 'Giảm giá đầu năm',
        discount: 20,
        type: 'Phần trăm',
        startDate: '2026-03-01',
        endDate: '2026-03-31',
        status: 'Đang áp dụng',
        usedCount: 45,
        maxUses: 100,
        description: 'Chương trình giảm giá đặc biệt chào mừng năm mới',
    },
    {
        id: 2,
        code: 'NEWCUSTOMER',
        name: 'Khách hàng mới',
        discount: 50000,
        type: 'Số tiền',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        status: 'Đang áp dụng',
        usedCount: 23,
        maxUses: 200,
        description: 'Ưu đãi dành riêng cho khách hàng mới',
    },
    {
        id: 3,
        code: 'BESTSELLER',
        name: 'Sách bán chạy',
        discount: 15,
        type: 'Phần trăm',
        startDate: '2026-03-15',
        endDate: '2026-04-15',
        status: 'Sắp diễn ra',
        usedCount: 0,
        maxUses: 150,
        description: 'Giảm giá các đầu sách bán chạy nhất',
    },
    {
        id: 4,
        code: 'WINTER2025',
        name: 'Khuyến mãi mùa đông',
        discount: 30,
        type: 'Phần trăm',
        startDate: '2025-12-01',
        endDate: '2026-02-28',
        status: 'Đã kết thúc',
        usedCount: 98,
        maxUses: 100,
        description: 'Chương trình khuyến mãi mùa đông',
    },
    {
        id: 5,
        code: 'STUDENT2026',
        name: 'Ưu đãi sinh viên',
        discount: 25,
        type: 'Phần trăm',
        startDate: '2026-03-01',
        endDate: '2026-06-30',
        status: 'Đang áp dụng',
        usedCount: 67,
        maxUses: 300,
        description: 'Giảm giá dành cho sinh viên',
    },
];