import { Employee } from '../employee/EmployeesPage';
export const mockEmployees: Employee[] = [
    {
        id: 1,
        employeeCode: 'NV001',
        name: 'A Nguyen Van',
        email: 'nguyen.vana@company.com',
        phone: '0901234567',
        position: 'Quản lý cửa hàng',
        department: 'Quản lý',
        joinDate: '2024-01-01',
        status: 'Đang làm việc',
        salary: 15000000,
    },
    {
        id: 2,
        employeeCode: 'NV002',
        name: 'Nguyễn Vũ Linh',
        email: 'nguyen.vulinh@company.com',
        phone: '0912345678',
        position: 'Nhân viên bán hàng',
        department: 'Bán hàng',
        joinDate: '2024-02-15',
        status: 'Đang làm việc',
        salary: 10000000,
    },
    {
        id: 3,
        employeeCode: 'NV003',
        name: 'Trần Thị B',
        email: 'tran.thib@company.com',
        phone: '0923456789',
        position: 'Kế toán',
        department: 'Tài chính',
        joinDate: '2024-03-10',
        status: 'Đang làm việc',
        salary: 12000000,
    },
    {
        id: 4,
        employeeCode: 'NV004',
        name: 'Lê Văn C',
        email: 'le.vanc@company.com',
        phone: '0934567890',
        position: 'Thủ kho',
        department: 'Kho vận',
        joinDate: '2024-04-20',
        status: 'Nghỉ phép',
        salary: 9000000,
    },
    {
        id: 5,
        employeeCode: 'NV005',
        name: 'Phạm Minh D',
        email: 'pham.minhd@company.com',
        phone: '0945678901',
        position: 'Nhân viên bán hàng',
        department: 'Bán hàng',
        joinDate: '2024-05-05',
        status: 'Đang làm việc',
        salary: 10000000,
    },
];
